language: python
sudo: required 

python:
  - "2.7"
  - "3.5"

env:
  - TOXENV=py27
  - TOXENV=py35
  - TOXENV=docs
  - TOXENV=linkcheck
  - TOXENV=codecov
  - TOXENV=pycodestyle

before_install:
  - sudo apt-get -qq update
  
install:
  - travis_retry pip install -U pip wheel setuptools
  - travis_retry pip install -r requirements.txt
  - python setup.py develop

script:
  - tox -e ${TOXENV}

after_success:
  - bash <(curl -s https://codecov.io/bash) -e ${TOXENV}
